/**
 * BeCoffee — Master Product Catalog & Fallback Data
 * Synchronized with MySQL database (41 artisanal offerings)
 */
window.DEFAULT_BECOFFEE_MENU = [
      // --- 1. HOUSE COFFEE (Iced M: 120 / L: 140 · Hot: 120) ---
      {
        id: 'hc-classic',
        category: 'house-coffee',
        name: 'Classic Coffee',
        origin: 'House Roast Blend',
        elevation: 'Hot / Iced',
        price: 120,
        priceIcedM: 120,
        priceIcedL: 140,
        priceHot: 120,
        description: 'Smooth, balanced house-brewed coffee with rich nutty undertones and a clean, satisfying finish.',
        tags: ['House Coffee', 'Daily Classic'],
        image: 'images/menu/hc-classic.webp',
        flavors: ['bold-coffee'],
        flavorLabels: ['Bold & Classic Coffee']
      },
      {
        id: 'hc-spanish',
        category: 'house-coffee',
        name: 'Spanish Latte',
        origin: 'Espresso & Sweetened Milk',
        elevation: 'Hot / Iced',
        price: 120,
        priceIcedM: 120,
        priceIcedL: 140,
        priceHot: 120,
        description: 'Velvety espresso combined with smooth fresh milk and rich condensed milk for a perfectly sweet kick.',
        tags: ['House Coffee', 'Crowd Favorite'],
        image: 'images/menu/hc-spanish.webp',
        flavors: ['sweet-caramel', 'bold-coffee'],
        flavorLabels: ['Sweet & Caramel', 'Bold Coffee']
      },
      {
        id: 'hc-americano',
        category: 'house-coffee',
        name: 'Americano',
        origin: 'Double Espresso & Water',
        elevation: 'Hot / Iced',
        price: 120,
        priceIcedM: 120,
        priceIcedL: 140,
        priceHot: 120,
        description: 'Bold, clean double shot of house espresso poured over hot water or crisp ice.',
        tags: ['House Coffee', 'Bold & Clean'],
        image: 'images/menu/hc-americano.webp',
        flavors: ['bold-coffee'],
        flavorLabels: ['Bold & Classic Coffee']
      },
      {
        id: 'hc-french-vanilla',
        category: 'house-coffee',
        name: 'French Vanilla Latte',
        origin: 'Espresso & French Vanilla',
        elevation: 'Hot / Iced',
        price: 120,
        priceIcedM: 120,
        priceIcedL: 140,
        priceHot: 120,
        description: 'Silky espresso and textured milk infused with sweet, aromatic French vanilla bean syrup.',
        tags: ['House Coffee', 'Fragrant Vanilla'],
        image: 'images/menu/hc-french-vanilla.webp',
        flavors: ['sweet-caramel'],
        flavorLabels: ['Sweet & Caramel']
      },
      {
        id: 'hc-coffee-latte',
        category: 'house-coffee',
        name: 'Coffee Latte',
        origin: 'Espresso & Fresh Milk',
        elevation: 'Hot / Iced',
        price: 120,
        priceIcedM: 120,
        priceIcedL: 140,
        priceHot: 120,
        description: 'The timeless coffeehouse essential with smooth textured milk folded into freshly pulled espresso.',
        tags: ['House Coffee', 'Smooth & Creamy'],
        image: 'images/menu/hc-coffee-latte.webp',
        flavors: ['bold-coffee'],
        flavorLabels: ['Bold & Classic Coffee']
      },
      {
        id: 'hc-caramel-macchiato',
        category: 'house-coffee',
        name: 'Caramel Macchiato',
        origin: 'Espresso, Vanilla & Caramel',
        elevation: 'Hot / Iced',
        price: 120,
        priceIcedM: 120,
        priceIcedL: 140,
        priceHot: 120,
        description: 'Layered vanilla-infused milk crowned with rich espresso and golden buttery caramel drizzle.',
        tags: ['Bestseller', 'Caramel Drizzle'],
        image: 'images/menu/hc-caramel-macchiato.webp',
        flavors: ['sweet-caramel'],
        flavorLabels: ['Sweet & Caramel']
      },
      {
        id: 'hc-salted-caramel',
        category: 'house-coffee',
        name: 'Salted Caramel',
        origin: 'Espresso & Flaky Sea Salt Caramel',
        elevation: 'Hot / Iced',
        price: 120,
        priceIcedM: 120,
        priceIcedL: 140,
        priceHot: 120,
        description: 'Slow-cooked rich caramel paired with espresso, fresh milk, and a delicate touch of flaky sea salt.',
        tags: ['Bestseller', 'Sweet & Savory'],
        image: 'images/menu/hc-salted-caramel.webp',
        flavors: ['sweet-caramel'],
        flavorLabels: ['Sweet & Caramel']
      },
      {
        id: 'hc-sea-salt-latte',
        category: 'house-coffee',
        name: 'Sea Salt Latte',
        origin: 'Espresso & Sea Salt Cold Cream',
        elevation: 'Hot / Iced',
        price: 120,
        priceIcedM: 120,
        priceIcedL: 140,
        priceHot: 120,
        description: 'Rich, comforting latte topped with velvety lightly salted cream for a sublime sweet-savory contrast.',
        tags: ['House Coffee', 'Sea Salt Cream'],
        image: 'images/menu/hc-sea-salt-latte.webp',
        flavors: ['sweet-caramel'],
        flavorLabels: ['Sweet & Caramel']
      },
      {
        id: 'hc-ube-latte',
        category: 'house-coffee',
        name: 'Ube Latte',
        origin: 'Espresso & Purple Yam Jam',
        elevation: 'Hot / Iced',
        price: 120,
        priceIcedM: 120,
        priceIcedL: 140,
        priceHot: 120,
        description: 'Vibrant handcrafted ube halaya blend with fresh milk and a smooth espresso float.',
        tags: ['House Coffee', 'Handcrafted Ube'],
        image: 'images/menu/hc-ube-latte.webp',
        flavors: ['sweet-caramel'],
        flavorLabels: ['Sweet & Caramel']
      },
      {
        id: 'hc-mocha',
        category: 'house-coffee',
        name: 'Mocha',
        origin: 'Espresso & Rich Dark Cocoa',
        elevation: 'Hot / Iced',
        price: 120,
        priceIcedM: 120,
        priceIcedL: 140,
        priceHot: 120,
        description: 'Decadent dark cocoa melted into freshly pulled espresso and steamed milk.',
        tags: ['House Coffee', 'Rich Cocoa'],
        image: 'images/menu/hc-mocha.webp',
        flavors: ['chocolate-malt', 'bold-coffee'],
        flavorLabels: ['Chocolate & Malt', 'Bold Coffee']
      },
      {
        id: 'hc-white-choco-mocha',
        category: 'house-coffee',
        name: 'White Chocolate Mocha',
        origin: 'Espresso & White Cacao',
        elevation: 'Hot / Iced',
        price: 120,
        priceIcedM: 120,
        priceIcedL: 140,
        priceHot: 120,
        description: 'Sweet, velvety white chocolate sauce paired with bold espresso and creamy textured milk.',
        tags: ['House Coffee', 'Sweet White Cocoa'],
        image: 'images/menu/hc-white-choco-mocha.webp',
        flavors: ['sweet-caramel', 'chocolate-malt'],
        flavorLabels: ['Sweet & Caramel', 'White Chocolate']
      },
      {
        id: 'hc-coffee-milo',
        category: 'house-coffee',
        name: 'Coffee Milo',
        origin: 'Espresso & Malted Milo Milk',
        elevation: 'Hot / Iced',
        price: 120,
        priceIcedM: 120,
        priceIcedL: 140,
        priceHot: 120,
        description: 'The ultimate power brew—rich espresso combined with hearty malted Milo chocolate milk.',
        tags: ['House Coffee', 'Malted Power Brew'],
        image: 'images/menu/hc-coffee-milo.webp',
        flavors: ['chocolate-malt', 'bold-coffee'],
        flavorLabels: ['Chocolate & Malt', 'Bold Coffee']
      },
      {
        id: 'hc-biscoff-latte',
        category: 'house-coffee',
        name: 'Biscoff Latte',
        origin: 'Espresso & Speculoos Cookie Butter',
        elevation: 'Hot / Iced',
        price: 120,
        priceIcedM: 120,
        priceIcedL: 140,
        priceHot: 120,
        description: 'Spiced Belgian caramelized cookie spread melted into hot or iced espresso and milk.',
        tags: ['House Coffee', 'Cookie Butter'],
        image: 'images/menu/hc-biscoff-latte.webp',
        flavors: ['sweet-caramel'],
        flavorLabels: ['Sweet & Caramel']
      },

      // --- 2. MATCHA (Iced M: 120 / L: 140 · Hot: 120) ---
      {
        id: 'mat-latte',
        category: 'matcha',
        name: 'Matcha Latte',
        origin: 'Uji Ceremonial Green Tea',
        elevation: 'Hot / Iced',
        price: 120,
        priceIcedM: 120,
        priceIcedL: 140,
        priceHot: 120,
        description: 'Stone-ground green tea whisked fresh with silky milk for a soothing, umami-rich experience.',
        tags: ['Bestseller', 'Pure Ceremonial'],
        image: 'images/menu/mat-latte.webp',
        flavors: ['matcha'],
        flavorLabels: ['Ceremonial Matcha']
      },
      {
        id: 'mat-dirty',
        category: 'matcha',
        name: 'Dirty Matcha',
        origin: 'Uji Matcha & Espresso Shot',
        elevation: 'Hot / Iced',
        price: 120,
        priceIcedM: 120,
        priceIcedL: 140,
        priceHot: 120,
        description: 'Earthy ceremonial matcha latte topped with a concentrated shot of dark espresso.',
        tags: ['Matcha', 'Espresso Float'],
        image: 'images/menu/mat-dirty.webp',
        flavors: ['matcha', 'bold-coffee'],
        flavorLabels: ['Ceremonial Matcha', 'Bold Coffee']
      },
      {
        id: 'mat-berry',
        category: 'matcha',
        name: 'Matcha Berry',
        origin: 'Uji Matcha & Wild Strawberry',
        elevation: 'Hot / Iced',
        price: 120,
        priceIcedM: 120,
        priceIcedL: 140,
        priceHot: 120,
        description: 'Layered handcrafted sweet berry compote with milk and crowned with frothy green matcha.',
        tags: ['Matcha', 'Sweet Berry Layer'],
        image: 'images/menu/mat-berry.webp',
        flavors: ['matcha', 'fruity-berry'],
        flavorLabels: ['Ceremonial Matcha', 'Fruity & Berry']
      },
      {
        id: 'mat-ube',
        category: 'matcha',
        name: 'Matcha Ube',
        origin: 'Uji Matcha & Purple Yam Jam',
        elevation: 'Hot / Iced',
        price: 120,
        priceIcedM: 120,
        priceIcedL: 140,
        priceHot: 120,
        description: 'Vibrant dual-color fusion of velvety purple yam and green ceremonial matcha tea.',
        tags: ['Matcha', 'Ube Fusion'],
        image: 'images/menu/mat-ube.webp',
        flavors: ['matcha', 'sweet-caramel'],
        flavorLabels: ['Ceremonial Matcha', 'Sweet & Caramel']
      },
      {
        id: 'mat-choco',
        category: 'matcha',
        name: 'Matchoco',
        origin: 'Uji Matcha & Cocoa Chocolate',
        elevation: 'Hot / Iced',
        price: 120,
        priceIcedM: 120,
        priceIcedL: 140,
        priceHot: 120,
        description: 'Deep cocoa chocolate swirled together with vibrant ceremonial green tea.',
        tags: ['Matcha', 'Choco Swirl'],
        image: 'images/menu/mat-choco.webp',
        flavors: ['matcha', 'chocolate-malt'],
        flavorLabels: ['Ceremonial Matcha', 'Chocolate & Malt']
      },
      {
        id: 'mat-caramel',
        category: 'matcha',
        name: 'Matcharamel',
        origin: 'Uji Matcha & Golden Caramel',
        elevation: 'Hot / Iced',
        price: 120,
        priceIcedM: 120,
        priceIcedL: 140,
        priceHot: 120,
        description: 'Ceremonial matcha latte drizzled with luscious buttery golden caramel syrup.',
        tags: ['Matcha', 'Golden Caramel'],
        image: 'images/menu/mat-caramel.webp',
        flavors: ['matcha', 'sweet-caramel'],
        flavorLabels: ['Ceremonial Matcha', 'Sweet & Caramel']
      },

      // --- 3. HOUSE SPECIALS (Iced M: 90 / L: 110 · Hot: 90) ---
      {
        id: 'hs-milo',
        category: 'house-specials',
        name: 'Milo',
        origin: 'Malted Chocolate Milk',
        elevation: 'Hot / Iced',
        price: 90,
        priceIcedM: 90,
        priceIcedL: 110,
        priceHot: 90,
        description: 'Rich, creamy malted chocolate beverage prepared hot or poured over cracked ice with malt powder.',
        tags: ['Bestseller', 'Nostalgia Classic'],
        image: 'images/menu/hs-milo.webp',
        flavors: ['chocolate-malt'],
        flavorLabels: ['Chocolate & Malt']
      },
      {
        id: 'hs-choco',
        category: 'house-specials',
        name: 'Choco',
        origin: 'Classic Dark Chocolate Milk',
        elevation: 'Hot / Iced',
        price: 90,
        priceIcedM: 90,
        priceIcedL: 110,
        priceHot: 90,
        description: 'Decadent, velvety chocolate milk made with pure cocoa and smooth fresh milk.',
        tags: ['House Special', 'Pure Chocolate'],
        image: 'images/menu/hs-choco.webp',
        flavors: ['chocolate-malt'],
        flavorLabels: ['Chocolate & Malt']
      },
      {
        id: 'hs-chocoberry',
        category: 'house-specials',
        name: 'Chocoberry',
        origin: 'Dark Chocolate & Berry Puree',
        elevation: 'Hot / Iced',
        price: 90,
        priceIcedM: 90,
        priceIcedL: 110,
        priceHot: 90,
        description: 'Indulgent sweet chocolate milk infused with real strawberry and mixed berry nectar.',
        tags: ['House Special', 'Berry & Choco'],
        image: 'images/menu/hs-chocoberry.webp',
        flavors: ['chocolate-malt', 'fruity-berry'],
        flavorLabels: ['Chocolate & Malt', 'Fruity & Berry']
      },

      // --- 4. YOGURT / SODA (Iced M: 80 / L: 100) ---
      {
        id: 'ys-strawberry',
        category: 'yogurt-soda',
        name: 'Strawberry',
        origin: 'Sweet Strawberry Puree',
        elevation: 'Iced Only',
        price: 80,
        priceIcedM: 80,
        priceIcedL: 100,
        priceHot: null,
        description: 'Crisp, refreshing sparkling soda or creamy yogurt drink infused with ripe strawberry puree.',
        tags: ['Yogurt / Soda', 'Iced Only'],
        image: 'images/menu/ys-strawberry.webp',
        flavors: ['fruity-berry'],
        flavorLabels: ['Fruity & Refreshing']
      },
      {
        id: 'ys-blueberry',
        category: 'yogurt-soda',
        name: 'Blueberry',
        origin: 'Wild Blueberry Puree',
        elevation: 'Iced Only',
        price: 80,
        priceIcedM: 80,
        priceIcedL: 100,
        priceHot: null,
        description: 'Tart and sweet wild blueberry syrup paired with effervescent soda or chilled probiotic yogurt.',
        tags: ['Yogurt / Soda', 'Iced Only'],
        image: 'images/menu/ys-blueberry.webp',
        flavors: ['fruity-berry'],
        flavorLabels: ['Fruity & Refreshing']
      },
      {
        id: 'ys-mixed-berries',
        category: 'yogurt-soda',
        name: 'Mixed Berries',
        origin: 'Raspberry, Blackberry & Blueberry',
        elevation: 'Iced Only',
        price: 80,
        priceIcedM: 80,
        priceIcedL: 100,
        priceHot: null,
        description: 'Vibrant blend of summer berries sparkling with crisp botanical soda or smooth yogurt.',
        tags: ['Yogurt / Soda', 'Iced Only'],
        image: 'images/menu/ys-mixed-berries.webp',
        flavors: ['fruity-berry'],
        flavorLabels: ['Fruity & Refreshing']
      },
      {
        id: 'ys-green-apple',
        category: 'yogurt-soda',
        name: 'Green Apple',
        origin: 'Crisp Green Apple Cordial',
        elevation: 'Iced Only',
        price: 80,
        priceIcedM: 80,
        priceIcedL: 100,
        priceHot: null,
        description: 'Zesty, bright green apple cordial served over ice with fizzy sparkling soda or creamy yogurt.',
        tags: ['Yogurt / Soda', 'Iced Only'],
        image: 'images/menu/ys-green-apple.webp',
        flavors: ['fruity-berry'],
        flavorLabels: ['Fruity & Refreshing']
      }
];
